version: '1.0'
services:
  db-dev:
    image: postgres
    ports:
      - 5434:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
      POSTGRES_DB: nest
    networks:
      - local
networks:
  local:
